export const outlets = [
  "BrewPoints Bukit Bintang",
  "BrewPoints KLCC",
  "BrewPoints Mid Valley",
  "BrewPoints Pavilion KL",
  "BrewPoints Sunway Pyramid",
  "BrewPoints 1 Utama",
  "BrewPoints The Gardens",
  "BrewPoints Nu Sentral",
  "BrewPoints Bangsar South",
  "BrewPoints Mont Kiara",
  "BrewPoints Desa ParkCity",
  "BrewPoints TTDI",
  "BrewPoints Bangsar Village",
  "BrewPoints Hartamas",
  "BrewPoints Kepong",
  "BrewPoints Cheras",
  "BrewPoints Ampang Point",
  "BrewPoints Wangsa Maju",
  "BrewPoints Setapak Central",
  "BrewPoints Danau Kota",
  "BrewPoints Subang Jaya",
  "BrewPoints Sunway Giza",
  "BrewPoints Kota Damansara",
  "BrewPoints Mutiara Damansara",
  "BrewPoints Ara Damansara",
  "BrewPoints IOI Mall Puchong",
  "BrewPoints Cyberjaya",
  "BrewPoints Putrajaya",
  "BrewPoints Shah Alam",
  "BrewPoints Klang Parade",
  "BrewPoints AEON Bukit Tinggi",
  "BrewPoints Penang Gurney",
  "BrewPoints Penang Queensbay",
  "BrewPoints JB City Square",
  "BrewPoints JB KSL City",
  "BrewPoints Melaka Mahkota",
  "BrewPoints Ipoh Parade",
  "BrewPoints Kuantan East Coast",
  "BrewPoints Kota Bharu KB Mall",
  "BrewPoints KK Imago",
  "BrewPoints Kuching Vivacity",
  "BrewPoints Bintulu Times Square",
];
